### PR TITLE
Added a wifi controller to the UI (v1.0)

### PR DESCRIPTION
**Pull request by mrsydster**
### NOTES:
- Works only for the **wlan0** adapter at the moment.
- No user feedback implemented yet (if you see the interface pop up in the bitrate section, succesful connection)
- Wifi settings will not hide and is also visible durint streaming since you can switch networks while streaming

- Tested using the **TP-Link AC1300 Archer T3U Plus**

### TODO:
- Proper user feedback (eg. 'Succesfully connected!')
- A way to select wifi for multiple wlanX adapters for those using more than 1

Let me know any feedback.

### CODE REVIEW

**Comment by rationalsa** [comment]
I've started to give this a try, however I had 2 wifi adapters fitted which may have affected things, plus some additional issues:

1) The latest `node-wifi` version that actually installs on top of the Uubntu 18.04 packages of node / npm is 2.0.7, starting with 2.0.10 it throws an error. So this may be causing some of the other issues.
1.1) Bumping up the bcrypt version breaks compatibility with the packaged nodejs stack as well. I very much don't want to get into the business of packaging nodejs, so I'd rather not add any such dependencies.
2) The refresh button seems to just clear the network list. `nmcli device wifi rescan ifname wlan0` does the job and gets the network list populated (but after a refresh, it doesn't get pushed).
3) At one point it wasn't listing the network I was actually connected to, and it was showing me connected to the second highest signal strength network.
4) The UI should allow connecting to known networks without entering the password again. It should also allow forgetting / deleting a known network.

I guess I'll install upstream nodejs and give it another try with the latest node-wifi.

I'd also like to clarify the licensing status of the refresh icon.

**Comment by mrsydster** [comment]
Good points, I am actually working on version two that does not use the node-wifi lib and has better user feedback.

**Comment by rationalsa** [comment]
Oh, thank you for working on a more refined version. In that case, I think it makes sense to delay a more detailed review until that version is ready?

In terms of UI, after trying this out and having looked at a few OS WiFi managers, this is what I have in mind:
* it should show a list of detected networks, rather than a drop down
* if connected to a network, it should be the first one listed (and maybe have a disconnect button?)
* the default action should be to connect when clicking on a network:
* if it's open or saved, it should do so immediately
* if it's not saved and it has encryption, it should prompt for a password
* saved networks should have a button to the right to forget / delete the network
* saved networks that aren't in range should be displayed at the bottom of the list so the forget / delete button is accessible

If there are multiple WiFi adapters, each one should have an instance of this UI (similarly to nmcli)

In terms of NetworkManager functionality, this would need to use scan results, connections and to match scan results to connections.

You don't have to implement everything yourself btw, feel free to update the pull request if you get to the point where you're bored of it or if you won't have the free time to work on it for a while.

**Comment by mrsydster** [comment]
@rationalsa Just updated the pull request according to the list below! 

Anyone wanting to try, please have a close look for any bugs before merging and feel free to refactor code where needed.

> In terms of UI, after trying this out and having looked at a few OS WiFi managers, this is what I have in mind:
> 
> * it should show a list of detected networks, rather than a drop down
> * if connected to a network, it should be the first one listed (and maybe have a disconnect button?)
> * the default action should be to connect when clicking on a network:
> * if it's open or saved, it should do so immediately
> * if it's not saved and it has encryption, it should prompt for a password
> * saved networks should have a button to the right to forget / delete the network
> * saved networks that aren't in range should be displayed at the bottom of the list so the forget / delete button is accessible
> 
> If there are multiple WiFi adapters, each one should have an instance of this UI (similarly to nmcli)
> 
> In terms of NetworkManager functionality, this would need to use scan results, connections and to match scan results to connections.

**Comment by mrsydster** [comment]
I did find an issue just now on my Nano 2GB where networks are not showing as known, because the connection profile does not set the interface-name. Looking into it.

**Comment by 715209** [comment]
Hey! This is awesome, b3ck and I gave it a try and we found that sometimes the `scan wifi list` doesn't load anything when already connected to a network.

It would also be nice to:
- Add the wifi frequency (2.4 GHz or 5 GHz) in cases where you're using the same SSID for both frequencies.
- Feedback to the user when clicking on a SSID, when pressing on an unprotected SSID it will just connect, this could happen by accident and the user wouldn't know.

**Comment by mrsydster** [comment]
Nice! Thanks for the feedback. I noticed the wifi list not showing anything as well.

The weird thing is, it seems to be a core wifi dongle thing. At that point, searching manually in cli does not show any networks neither.

**Comment by rationalsa** [comment]
Thanks for the PR again. As agreed with @mrsydster on Discord, I'll continue development of this feature in the new `wifi` branch as I want to do some modifications and improvements before merging it in the main `ws_nodejs` branch.

These are my notes for now:

Support for multiple WiFi adapters ✓
---
* should be fully working by the time I merge it in the main branch
* they show up as separate bootstrap cards ✓
* network status is shown correctly for each adapter ✓
* disconnecting works correctly for each adapter ✓
* adding a new connection registers it with the correct adapter ✓
* deleting known networks removes the correct connection ✓
* ~~might want to show a vendor / product name for each one~~
* scanning scans on all interfaces - not necessarily a bad thing, but it's pretty jarring to see all the network lists disappearing

The empty network list issue already mentioned here ✓
---
I believe this might be a misunderstanding of how WiFi scanning works with NetworkManager: at least while connected to a network, the device needs to be issued a rescan command, and once it has the results, it will asynchronously start returning an updated list. I believe an empty list just means that the previous scanning results were stale and have been discarded. nmcli will probably have to be polled for new results until the result is updated.

Associating connections with an ifname ✓
---
It isn't a good idea, because the name of the interface can change between reboots, if additional WiFi adapters are plugged in, if there's an USB glitch, etc. Ubuntu 18.04 as distributed for Jetson Nano doesn't use persistent interface names. This was also making the WiFi manager ask for the password and create new NM connections when trying to connect to networks already known to NM. Furthermore, this is redundant. NetworkManager already associates the connections with the WiFi adapter's MAC address. We'll need to get the MAC address of each adapter with `nmcli --terse --fields general.hwaddr device show <ifname>` to match it to connections.

Incomplete network list (because of the signal strength threshold) ✓
---
I think I'll remove this. The value reported is kind of arbitrary and somewhat specific to the WiFi adapter in use. Don't want to end up hiding potentially usable networks.

'--' networks ✓
---
~~nmcli reports some networks with the `--` SSID. I need to check whether these are 'hidden' networks which don't broadcast their ESSID or something else that needs to be handled.~~
Edit: they're hidden networks, they'll be excluded from the search results for now

broadcasting changes asynchronously  ✓
---
status changes (e.g. updated scan results, connections / disconnections, adding and removing WiFi adapters) should be broadcast to the connected belaUI clients and the remote
Using the nmcli approach, will probably have to track the status in belaUI, poll nmcli periodically and send the updated status to the connected clients if it changes.

Edit: nmcli turns out to be very CPU/power-heavy. Polling it periodically the entire time belaUI is running would be bad. Currently working on a way to track WiFi status using the periodic ifconfig polling that belaUI is already doing and only calling nmcli when something has changed. ✓

Network filtering  ✓
---
I believe at the moment only PSK/WPA-Personal auth is supported, without EAP auth / WPA2-Enterprise. These results should be either hidden, or the UI should show the user that they're unsupported.

Error reporting  ✓
---
An error should be reported if the authentication fails. TODO: check if this is handled atm. The connection created by NM should also be removed

API  ✓
---
I'll redesign it to move everything WiFi manager-related in a separate 'namespace' 

UI
---
* Remove some of the vertical padding for the network list to take up less screen space  ✓
* When connecting to a new network, pressing enter in the password field should submit the form  ✓
* Add show/hide toggle button to the wifi password field  ✓
* WiFi manager UI state should be reset when disconnecting / reconnecting from the backend - noticed the network lists remain populated  ✓
* UI: show WiFi interface cards sorted by interface name  ✓
* Known networks should probably be shown even when out of range to allow them to be removed - maybe hidden by default by a hide / show button?  ✓

From mrsydster's todo
---
* Proper user feedback (eg. 'Succesfully connected!') ✓

From @715209's notes:
* Add the wifi frequency (2.4 GHz or 5 GHz) in cases where you're using the same SSID for both frequencies  ✓
  * ~~check if NM actually associates connections with a BSSID. Should it? It would be very annoying to have to create connections for every single AP used in a bigger WiFi deployment. IMO roaming should be allowed as long as the ESSID matches and the auth succeeds.~~
  * Edit: we're showing the frequency, but only one entry will be shown when there are multiple APs with the same SSID - either the one we're connected to, or if disconnect the highest signal AP ✓
* Feedback to the user when clicking on a SSID, when pressing on an unprotected SSID it will just connect, this could happen by accident and the user wouldn't know. ✓
  * ask for confirmation before connecting to open networks ✓

**Pull request closed without merging**
